# Generated by Django 3.2.5 on 2021-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('size', models.CharField(max_length=10, verbose_name='Talla')),
                ('color', models.CharField(max_length=25, verbose_name='Color')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('description', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('category', models.CharField(max_length=150, verbose_name='Categoria')),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
