# Generated by Django 3.2.5 on 2021-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0002_auto_20210710_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_user',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Dirección'),
        ),
    ]
