# Generated by Django 3.2.5 on 2021-07-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0002_auto_20210723_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('damas', 'Damas'), ('caballeros', 'Caballeros'), ('niños', 'Niños')], max_length=150, verbose_name='Categoria'),
        ),
    ]
